const RATE=59000, feeRate=.012; const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s); const money=n=>`$${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}`).classList.add('active')});
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));$$('[id$="-panel"]').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$(`#${b.dataset.mode}-panel`).classList.remove('hidden')});
function updateUsd(){let u=+$('#usd-send').value||0, c=$('#country').value, rates={NGN:1600,GHS:15.3,KES:129.5,USD:1}, symbols={NGN:'₦',GHS:'GH₵',KES:'KSh',USD:'$'};$('#usd-btc').textContent=`≈ ${(u/RATE).toFixed(6)} BTC`;$('#recipient-amount').textContent=`${symbols[c]}${(u*rates[c]).toLocaleString(undefined,{minimumFractionDigits:2})}`;$('#recipient-currency').textContent=`${c} recipient amount · Demo FX rate`};$('#usd-send').oninput=updateUsd;$('#country').onchange=updateUsd;updateUsd();
function updateBtc(){let b=+$('#btc-send').value||0;$('#btc-usd').textContent=`≈ ${money(b*RATE)} USD`;$('#btc-total').textContent=`${(b+.000012).toFixed(6)} BTC`};$('#btc-send').oninput=updateBtc;updateBtc();
function updateUser(){let a=+$('#user-amount').value||0, btc=$('#user-currency').value==='BTC';$('#user-equivalent').textContent=btc?`≈ ${money(a*RATE)} USD`:`≈ ${(a/RATE).toFixed(6)} BTC`};$('#user-amount').oninput=updateUser;$('#user-currency').onchange=updateUser;updateUser();
function updateRequest(){let a=+$('#request-amount').value||0,btc=$('#request-currency').value==='BTC';$('#request-equivalent').textContent=btc?`≈ ${money(a*RATE)} USD`:`≈ ${(a/RATE).toFixed(6)} BTC`};$('#request-amount').oninput=updateRequest;$('#request-currency').onchange=updateRequest;updateRequest();
$('#generate-request').onclick=()=>{let a=$('#request-amount').value,c=$('#request-currency').value;$('#request-title').textContent=`Pay ${c==='USD'?'$':''}${a} ${c} → Michael`;$('#request-link').textContent=`nexos.app/pay/michael-${a}`;$('#request-card').classList.remove('hidden')};$('#copy-request').onclick=()=>toast('Payment link copied');
function updateConvert(){let b=+$('#convert-btc').value||0,g=b*RATE,f=g*feeRate;$('#convert-usd').textContent=`≈ ${money(g)} USD`;$('#convert-fee').textContent=money(f);$('#final-usd').textContent=money(g-f)}$('#convert-btc').oninput=updateConvert;updateConvert();let seconds=45;setInterval(()=>{$('#timer').textContent=`00:${String(seconds=seconds?seconds-1:45).padStart(2,'0')}`},1000);
$$('[data-review]').forEach(b=>b.onclick=()=>{$('#review-title').textContent=b.dataset.review;$('#review').classList.remove('hidden')});$('.close').onclick=()=>$('#review').classList.add('hidden');$('#confirm').onclick=()=>{$('#review').classList.add('hidden');toast('Transaction submitted for secure processing')};$('#scan').onclick=()=>toast('QR scanner is ready');$('#user-search').oninput=e=>{$('#user-match').classList.toggle('hidden',!e.target.value)};
