const BTC_USD_PRICE = 63722.20;
let mode = 'fiat';
const amount = document.getElementById('amount');
const toast = document.getElementById('toast');
const modal = document.getElementById('modal');
const modalContent = document.getElementById('modal-content');
const setVisibility = () => document.querySelectorAll('.fiat-fields').forEach(el => el.classList.toggle('hidden', mode !== 'fiat')) || document.querySelectorAll('.btc-fields').forEach(el => el.classList.toggle('hidden', mode !== 'btc'));
function sendValue() { return Number(amount.value.replace(/[^0-9.]/g, '')) || 0; }
function formatAmount(value) { return mode === 'btc' ? `${value.toFixed(8)} BTC` : `$${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function updateAmount() { const value = sendValue(); document.getElementById('conversion-value').textContent = mode === 'btc' ? `$${(value * BTC_USD_PRICE).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} USD` : formatAmount(value); document.querySelectorAll('[data-amount]').forEach(btn => btn.classList.toggle('active', mode === 'fiat' && Number(btn.dataset.amount) === value)); document.querySelectorAll('[data-btc]').forEach(btn => btn.classList.toggle('active', mode === 'btc' && Number(btn.dataset.btc) === value)); }
function closeModal() { modal.classList.add('hidden'); }
function openModal(html) { modalContent.innerHTML = html; modal.classList.remove('hidden'); }
document.querySelectorAll('[data-mode]').forEach(button => button.addEventListener('click', () => { mode = button.dataset.mode; document.querySelectorAll('[data-mode]').forEach(btn => btn.classList.toggle('active', btn === button)); document.getElementById('balance-label').textContent = mode === 'btc' ? 'Available Bitcoin balance' : 'Available USD balance'; document.getElementById('balance-value').textContent = mode === 'btc' ? '0.08250000 BTC' : '$4,826.40'; document.getElementById('balance-note').textContent = mode === 'btc' ? '≈ $5,255.08 USD' : 'NIXXA USD Wallet'; document.getElementById('amount-currency').textContent = mode === 'btc' ? 'BTC' : 'USD'; amount.value = mode === 'btc' ? '0.005' : '100'; setVisibility(); updateAmount(); }));
document.querySelectorAll('[data-amount]').forEach(button => button.addEventListener('click', () => { amount.value = button.dataset.amount === 'max' ? '4826.40' : button.dataset.amount; updateAmount(); }));
document.querySelectorAll('[data-btc]').forEach(button => button.addEventListener('click', () => { amount.value = button.dataset.btc === 'max' ? '0.0825' : button.dataset.btc; updateAmount(); }));
amount.addEventListener('input', updateAmount);
document.getElementById('send-form').addEventListener('submit', event => { event.preventDefault(); const recipient = mode === 'btc' ? document.getElementById('btc-address').value.trim() : document.getElementById('fiat-account').value.trim(); if (!recipient || sendValue() <= 0) { toast.textContent = 'Enter a recipient and transfer amount'; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 1800); return; } const name = mode === 'fiat' ? document.getElementById('fiat-name').value.trim() || 'Recipient' : 'Bitcoin wallet'; openModal(`<h2>Review transfer</h2><p class="lead">Confirm your ${mode === 'btc' ? 'Bitcoin' : 'USD'} transfer.</p><div class="review-rows"><div><span>Recipient</span><b>${name}</b></div><div><span>${mode === 'btc' ? 'Wallet address' : 'Account'}</span><b>${recipient}</b></div><div><span>Amount</span><b>${formatAmount(sendValue())}</b></div><div><span>Transfer fee</span><b>${mode === 'btc' ? '0.0001 BTC' : '$0.00'}</b></div></div><div class="review-actions"><button id="cancel">Cancel</button><button class="primary" id="confirm">Confirm send</button></div>`); document.getElementById('cancel').addEventListener('click', closeModal); document.getElementById('confirm').addEventListener('click', processSend); });
function processSend() { openModal(`<div class="loader"></div><h2>Processing transfer</h2><p class="lead">Please wait while we send your funds.</p>`); setTimeout(() => openModal(`<div class="success">&#10003;</div><h2>Transfer initiated</h2><p class="lead">Your transfer is now being processed.</p><div class="review-actions"><button class="primary" id="done">Done</button></div>`), 1200); setTimeout(() => { const done = document.getElementById('done'); if (done) done.addEventListener('click', closeModal); }, 1250); }
document.getElementById('close').addEventListener('click', closeModal); modal.addEventListener('click', e => { if (e.target === modal) closeModal(); });
document.getElementById('scan').addEventListener('click', () => { toast.textContent = 'QR scanner is ready to connect'; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 1800); });
document.getElementById('help').addEventListener('click', () => { toast.textContent = 'NIXXA support is ready to help'; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 1800); });
setVisibility(); updateAmount();