const toast = document.getElementById('toast');
const panels = document.querySelectorAll('.panel');
const showToast = message => { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 1800); };
const openPanel = id => { panels.forEach(panel => panel.classList.add('hidden')); document.getElementById(id).classList.remove('hidden'); window.scrollTo(0, 0); };
document.getElementById('settings').addEventListener('click', () => openPanel('settings-screen'));
document.querySelectorAll('[data-open]').forEach(button => button.addEventListener('click', () => openPanel(button.dataset.open)));
document.querySelectorAll('.panel-back').forEach(button => button.addEventListener('click', () => panels.forEach(panel => panel.classList.add('hidden'))));
document.querySelectorAll('[data-toast]').forEach(button => button.addEventListener('click', event => { event.preventDefault(); showToast(button.dataset.toast); }));
document.querySelectorAll('.switch input').forEach(input => input.addEventListener('change', () => showToast(input.checked ? 'Preference saved' : 'Preference turned off')));
document.getElementById('copy-referral').addEventListener('click', () => { navigator.clipboard?.writeText('nixxa.app/r/JOHN829'); showToast('Referral link copied'); });
document.getElementById('profile-form').addEventListener('submit', event => { event.preventDefault(); showToast('Profile changes saved'); });
const modal = document.getElementById('logout-modal');
document.getElementById('logout').addEventListener('click', () => modal.classList.remove('hidden'));
document.getElementById('stay').addEventListener('click', () => modal.classList.add('hidden'));
modal.addEventListener('click', event => { if (event.target === modal) modal.classList.add('hidden'); });
document.getElementById('confirm-logout').addEventListener('click', () => { modal.classList.add('hidden'); showToast('You have been logged out'); });